### ISSUE TITLE
Address Hook Packet Receive

### ISSUE THREAD

**Issue by rizkyblackhat** [MapleStoryA/KitterzPE-Au-Edition#1]
Hi sir, do you still have aob packet receive / au.exe redbana 6 month ago that have same address in this source?

**Comment by devdilson** [comment]
Hi. 

Yes.

The receive packet is at ECX register of this AOB location: 8D 4C 24 08 E8 ?? ?? ?? ?? 8B 88

The packet has the following structure:

Length: 2 Bytes and includes the length value itself, therefore data length = length - 2.
Header: 2 byte, composed by packet type and subtype.
Data: (length - 2) bytes.

**Comment by rizkyblackhat** [comment]
Damn, thank you mate. Hope i can found it in Audition Ayodance.

**Comment by rizkyblackhat** [comment]
How about address 0x931BF0 in RecvHook mate?

**Comment by devdilson** [comment]
> How about address 0x931BF0 in RecvHook mate?

Unfortunately I have no idea, but you can use IDA to find it based on the AOB above
